# Generated by Django 3.2.20 on 2023-08-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Рецепт/Ингредиент', 'verbose_name_plural': 'Рецепты/Ингредиенты'},
        ),
    ]
