# Generated by Django 3.2.20 on 2023-08-24 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230823_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать только буквы, цифры и символы: @/./+/-/_', regex='^[\\w.@+-]+\\z')], verbose_name='Логин'),
        ),
    ]
